plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
theme: minima
markdown: GFM
minima:
  social_links: []
  enable_header_nav: true
    - about.md
    - publications.md
