title: "Jinu Jayachandran"
description: "Assistant Professor | CET | Wireless Communication, OTFS, Optimization"
email: "your.email@example.com"

baseurl: "" # for user pages
url: "https://yourusername.github.io"

theme: jekyll-theme-cayman

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
