title: "Jinu Jayachandran"
email: "your.email@example.com"
description: >-
  Assistant Professor | Wireless Communication | Optimization | Microcontrollers
baseurl: "" # keep it blank for user site
url: "https://yourusername.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-archives

markdown: kramdown
kramdown:
  input: GFM

minimal_mistakes_skin: "air"  # try also: default, dark, mint, neon, contrast

author:
  name   : "Jinu Jayachandran"
  avatar : "/assets/images/profile.jpg"
  bio    : "Ph.D. | Zak-OTFS | Assistant Professor, CET"
  location: "Trivandrum, India"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:your.email@example.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/yourusername"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/yourprofile"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true

header_pages:
  - about.md
  - research.md
  - teaching.md
  - blog.md
  - contact.md

footer:
  links:
    - label: "Privacy"
      url: "/privacy/"
    - label: "Terms"
      url: "/terms/"
