remote_theme: "nicolas-van/jekyll-cv@gh-pages"

title: "Dr. Jinu Jayachandran"
description: "Ph.D. (IIT Delhi) | Assistant Professor | Wireless Communication | Optimization"

name: "Jinu Jayachandran"
email: "your.email@example.com"
tel: "+91-9876543210"
website: "https://yourusername.github.io"

github: "yourusername"
linkedin: "your-linkedin-profile"
scholar: "https://scholar.google.com/citations?user=JaImdO8AAAAJ"

address:
  street: "Department of Electronics and Communication"
  city: "College of Engineering Trivandrum"
  zip: "695016"
  region: "Kerala"
  country: "India"

sections:
  - about
  - education
  - experience
  - publications
  - teaching
  - skills
  - links
